### ISSUE TITLE
module index headings are not the right colour

### ISSUE THREAD

**Issue by classabbyamp** [miaowware/miaowware-sphinx-theme#2]
https://gridtools.miaow.io/en/stable/py-modindex.html

![image](https://user-images.githubusercontent.com/5366828/102740370-9e11a080-431d-11eb-8a3a-6ef3b0543e46.png)

**Comment by 0x5c** [comment]
It seems to also affect other similar headings

**Comment by classabbyamp** [comment]
Could not find any other headings with the same issue. Do you remember what they were?

**Comment by 0x5c** [comment]
I don't really remember, but I think that it was just those and maybe something in the search results??
